// <auto-generated />
namespace YazLab1_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Yazlab : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Yazlab));
        
        string IMigrationMetadata.Id
        {
            get { return "202311041212347_Yazlab"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
